name: Continious integration

on: [push]

jobs:

    build:
  
      runs-on: ubuntu-latest
  
      steps:
  
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Download JAR to current dir
          run: mvn dependency:copy -Dartifact=com.google.crypto.tink:tink:1.3.0 -DoutputDirectory=.
        
        - name: Patch JAR
          run: gradle --project-dir patcher :run -P patcher.args='../tink-1.3.0.jar ../tink-android-1.3.0.${{ github.run_number }}.jar'

        - name: Deploy JAR to GitHub Packages
          run: |
            curl \
              --upload-file tink-android-1.3.0.${{ github.run_number }}.jar \
              --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
              https://maven.pkg.github.com/swapii/google-tink-android/com/github/swapii/google-tink-android/tink-android/1.3.0.${{ github.run_number }}/

        - name: Download POM to current dir
          run: mvn dependency:copy -Dartifact=com.google.crypto.tink:tink:1.3.0:pom -DoutputDirectory=.

        - name: Generate POM
          run: cat tink-android.pom | sed -E 's/(<version>).+(<\/version>)/\11.3.0.${{ github.run_number }}\2/' > tink-android-1.3.0.${{ github.run_number }}.pom

        - name: Deploy POM to GitHub Packages
          run: |
            curl \
              --upload-file tink-android-1.3.0.${{ github.run_number }}.pom \
              --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
              https://maven.pkg.github.com/swapii/google-tink-android/com/github/swapii/google-tink-android/tink-android/1.3.0.${{ github.run_number }}/
    