name: Continious integration

on: [push]

jobs:

    build:
  
      runs-on: ubuntu-latest
  
      steps:
  
      - name: Maven version
        run: mvn --version

      - name: Checkout sources
        uses: actions/checkout@v2

