name: Continious integration

on: [push]

jobs:

    build:
  
      runs-on: ubuntu-latest
  
      steps:
  
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Download Google Tink
          run: mvn dependency:get -DgroupId=com.google.crypto.tink -DartifactId=tink -Dversion=1.3.0

        - name: Copy Google Tink to current dir
          run: mvn dependency:copy -Dartifact=com.google.crypto.tink:tink:1.3.0 -DoutputDirectory=.
        
        - name: Print current dir files
          run: pwd && ls -la .
